# Generated by Django 5.1 on 2025-03-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='F52HbucJdCk5tEhUef6Dyyop2TPGMrT8NrWWntVAIITIKZsgPL', max_length=20, unique=True),
        ),
    ]
