# Generated by Django 5.1 on 2025-03-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='8euQBpHqbDa4AojmReEJg7jGr3SURN284PZmB1kwiTSm2EpQYw', max_length=20, unique=True),
        ),
    ]
