# Generated by Django 5.1 on 2025-03-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_username_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='OAbCNnmRzQCk3Ujh2o32P0TlfMtuRFMjFVZAtiR6MDKaw8Mci6', max_length=20, unique=True),
        ),
    ]
