# Generated by Django 5.1 on 2025-03-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='QQgRe4IgmSFY5GgTeIlvzLjWiYU77e2pL82s4K7gLLmrvRf1l5', max_length=20, unique=True),
        ),
    ]
