# Generated by Django 5.1 on 2025-03-07 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_review_rating_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('mail', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='connections',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='EX5bMA7SBL883DMKJWPR5PCU4aOGl7S5DQmEpfi0lsmsLMTdy5', max_length=20, unique=True),
        ),
    ]
