# Generated by Django 5.1 on 2025-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='KucliuFO3XWNmzueQNvaNH9qN3Ixn8gdf8onptXH4eJei8B5PG', max_length=20, unique=True),
        ),
    ]
