# Generated by Django 5.1 on 2025-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('mail', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=5000)),
            ],
        ),
    ]
