# Generated by Django 4.2.5 on 2024-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='McYk1l3fDtXJbzLP3282TAgXaTQ1HJCSnYojIaIkTxPigS0691', max_length=20, unique=True),
        ),
    ]
