# Generated by Django 4.2.5 on 2024-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0002_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='dlWXOL2tMsiPpP7BdH7jZsYqo1hWohfSt41G4FyTssh2OlZS9h', max_length=20, unique=True),
        ),
    ]
