# Generated by Django 4.2.5 on 2024-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0003_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='EfMCo7McrYOx5DVHoKZl1qcjWuBdn8oQZV53l21DNrouJj8eAA', max_length=20, unique=True),
        ),
    ]
