# Generated by Django 4.2.5 on 2024-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0004_skills_alter_users_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='categories',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='users',
            name='section',
        ),
        migrations.AddField(
            model_name='users',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='Ryne2J9QAaS5hxfjxbGqkywFtd6pGrYZHrffdYBQsFeMBxXMKr', max_length=20, unique=True),
        ),
    ]
