# Generated by Django 4.2.5 on 2024-02-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0005_rename_categories_users_skills_remove_users_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='followers',
            field=models.JSONField(default='[]'),
        ),
        migrations.AlterField(
            model_name='users',
            name='following',
            field=models.JSONField(default='[]'),
        ),
        migrations.AlterField(
            model_name='users',
            name='skills',
            field=models.JSONField(default='[]'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='kQC7FiOXZFVxOgQJzcqCVsJZDtoYKhfK0FTX8MJMQ4fioa6Z9Y', max_length=20, unique=True),
        ),
    ]
