# Generated by Django 4.2.5 on 2025-02-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0006_alter_users_followers_alter_users_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location1',
            field=models.CharField(default='United States of America', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='VqBih8523SSporMY1EbF6zX7wTNhtfDSWSx8EnvylifcPF9Akb', max_length=20, unique=True),
        ),
    ]
