# Generated by Django 4.2.5 on 2025-02-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0007_alter_users_location1_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='7iC0GOipILf8tn5RJBDrAFzux03DVeYddM5Fr3Z6oxFGaCfsKU', max_length=20, unique=True),
        ),
    ]
