# Generated by Django 5.1 on 2025-02-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0008_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='5q9wNoiONbzX1urSsUZBJjZW9EqyA568bLYJJHiVIlmx5lMS5A', max_length=20, unique=True),
        ),
    ]
