# Generated by Django 5.1 on 2025-03-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixcoverapp', '0009_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='um3OKbeOV5J5qnSiyv8LteOXp9CG55b9yvIJiYHaWrtxPnjyZi', max_length=20, unique=True),
        ),
    ]
